### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by nWidart** [mpedrera/themify#2]
Hi,

First of all I chose your package over others because it does one thing, and does it well. :smile: 

Do you plan on maintaining this package for the upcoming laravel 5 release?
I tried using it in a L5 app I'm building, and got a `Call to undefined method Illuminate\Routing\Controller::setFilterer()` error, commenting out line 71 (`Controller::setFilterer($router);`) of the resolver class fixed it, but not sure if it breaks anything.

Cheers,

**Comment by nWidart** [comment]
To anyone who needs this in a laravel 5 application, I'm working on a new version that will be compatible. Plus add some more features to the package.

Will be coming very soon.

**Comment by mpedrera** [comment]
@nWidart sorry for the late reply, this was buried in GitHub notifications :sweat_smile:. Unfortunately this project is no longer maintained, but I'd be happy to put a link to your new version in this repo's readme once you have it ready.
